### PR TITLE
fix: Fix path to type declarations

### PR DESCRIPTION
**Pull request by bmaupin**
I fixed the path to the type declarations in package.json. I also recently added the upstream package types to the DefinitelyTyped project (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56620), and since they were merged I've updated the types here with a few minor changes so they match.

I didn't know if I should bump the version number since the last version wasn't published.

Thanks!

### CODE REVIEW

**Review by myndzi — APPROVED** [review]

**Comment by myndzi** [comment]
Can't merge while a draft, is there some pending changes you still want to add?

**Comment by bmaupin** [comment]
Hi, sorry about that. I made an additional change upstream to the types for winston-syslog (which uses the glossy types I created) and I ran into a possible issue so I made this a draft just in case it needed further changes. But it seems like everything was fine in the end. Thanks!

**Comment by myndzi** [comment]
Bumped and published

**Comment by bmaupin** [comment]
Thanks!

**Pull request merged**
